<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-AVRBRCH" ignored="0" name="retry logic" tests="8" failures="2" timestamp="06 Oct 2018 19:54:15 GMT" time="0.103" errors="0">
  <testcase name="RetryTest" time="0.023" classname="com.qa.retry.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest -->
  <testcase name="RetryTest" time="0.003" classname="com.qa.retry.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest -->
  <testcase name="RetryTest" time="0.003" classname="com.qa.retry.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest -->
  <testcase name="RetryTest" time="0.002" classname="com.qa.retry.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.qa.retry.RetryLogic.RetryTest(RetryLogic.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- RetryTest -->
  <testcase name="RetryTest1" time="0.002" classname="com.qa.retry.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest1 -->
  <testcase name="RetryTest1" time="0.001" classname="com.qa.retry.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest1 -->
  <testcase name="RetryTest1" time="0.003" classname="com.qa.retry.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest1 -->
  <testcase name="RetryTest1" time="0.002" classname="com.qa.retry.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.qa.retry.RetryLogic.RetryTest1(RetryLogic.java:25)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- RetryTest1 -->
</testsuite> <!-- retry logic -->
